"""updating Balance Model

Revision ID: 7377bd7f3b10
Revises: 
Create Date: 2024-09-16 17:08:17.878257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7377bd7f3b10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('declared', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('amount_unit',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('measurement',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('measurement_unit',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('imported', schema=None) as batch_op:
        batch_op.alter_column('amount_unit',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('measurement',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('measurement_unit',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imported', schema=None) as batch_op:
        batch_op.alter_column('measurement_unit',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
        batch_op.alter_column('measurement',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('amount_unit',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)

    with op.batch_alter_table('declared', schema=None) as batch_op:
        batch_op.alter_column('measurement_unit',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
        batch_op.alter_column('measurement',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('amount_unit',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
