"""Your migration message

Revision ID: 9037362492a5
Revises: 7377bd7f3b10
Create Date: 2024-09-30 17:06:16.157093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9037362492a5'
down_revision = '7377bd7f3b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.alter_column('declaration_number',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'declared', ['declaration_number'], ['declaration_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('declaration_number',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=False)

    # ### end Alembic commands ###
